### PR TITLE
Fix issue #104 - Bug: HotReload Exception with Composite

### PR DESCRIPTION
**Pull request by tmohme**
@javabrett 
I fixed the root cause of the problem in the `BaseScannerManager` class.  
Unfortunately, creating automated tests for the hot-reloading mechanism is really difficult, because (among other things) the `AppBeforeIntegrationTestTask` disables scanning for integration tests.
In any case I was unable to find any integration tests for the hot-reload mechanism that I could build upon.  
Instead, I documented a recipe for a semi-automatic hot-reload test in the new `helloGrettyMultiproject` integration test.

### CODE REVIEW

**Comment by tmohme** [comment]
. . . to trigger a new build in travis (previous one had problems with „apt-get -pp updare“)

**Comment by tmohme** [comment]
F**ing travis - this time the tomcat7 build stalled (succeeded in previous run) while the "apt get -qq update" problems of the previous run vanished.

**Comment by javabrett** [comment]
Thanks for the PR - I've not forgotten/ignored this, but circumstances have meant that I haven't been able to look at it yet.  Won't be too long now.

**Comment by javabrett** [comment]
Thanks for your patience and the PR.  I have some time set-aside next month to do some work on Gretty, so I should be able to get to this then.

**Comment by michaelmosmann** [comment]
do you need any help with that?

**Comment by henrik242** [comment]
@tmohme  Can you rebase this on the latest changes?

**Comment by tmohme** [comment]
Sorry, but it's over nine months since I created the PR.
We had to come up with a solution and left pretty behind long ago.
I don't even remember the details what the problem was all about.
Feel free to use the changes from the PR as you like.

**Comment by tray2100** [comment]
@javabrett what's the likelihood that this will make it into an upcoming release? It would help me and a lot of other folks out here facing this issue.

**Comment by boris-petrov** [comment]
@tray2100 - can you confirm that this PR fixes the issue? That is, can you build Gretty from source from this branch and let us know?

**Comment by tray2100** [comment]
@boris-petrov I will try to do so this weekend and let you know. Do you guys have a slack channel or anything for this project? Or do you just communicate via PR/Issues?

**Comment by boris-petrov** [comment]
Thanks, keep us posted on the result.

We just use PRs and issues, yes. I'll work on creating a Gitter chat room.

**Comment by boris-petrov** [comment]
@tray2100 - there is now a [Gitter room](https://gitter.im/gretty-gradle-plugin/gretty) that you/we can use for chatting about Gretty.

**Comment by gbalthasar** [comment]
Ok, I manually merged the PR into my own fork, and managed to partially upgrade gretty to my own 3.0.4-SNAPSHOT version. Error: NullPointer in module gretty-runner Runner.java at line 41

I fixed this too (writer is null) by changing line to:
`if (writer) writer.writeMayFail(json.toString())`

I also managed to upgrade the runner to my 3.0.4-SNAPSHOT version and now everything works as expected.

So with the additional change, the PR can be merged for the next version.

**Comment by boris-petrov** [comment]
@tray2100, @gbalthasar - I rebased the branch on Gretty master because it wasn't targeted there and wasn't up to date. Can you please try out the branch again, pulling the latest version? I want to see if this change that @gbalthasar proposes is needed - perhaps it has already been fixed along the way. If one/both of you say that the branch works, we can merge it.

**Comment by gbalthasar** [comment]
@boris-petrov - I looked up the Runner.groovy (only on github though) at branch master and branch gretty4 and in both branches the change I proposed above is still needed in line 41:

`if (writer) writer.writeMayFail(json.toString())`

I'm sorry I cannot help further. I already took me half a day to get the PR into my own fork and getting my gretty project to run with the modified plugin. I really don't know how to test a complete new version as gradle doesn't pull transitive dependencies when using file(...) for jars. I got it working by using the regular plugin notation with version '3.0.3' and replacing gretty and gretty-runner jars additionally. So gretty pulled the dependencies from '3.0.3' but replaced the two jars.

Can't you just modify the PR with the change (completly uncritical, te output is still printed from a previous ServerStartEventImpl instance) and merge it against master again?

**Comment by boris-petrov** [comment]
@javabrett, @henrik242, @f4lco - I suggest we merge this PR. It obviously helps people so if none of you bring up any objections/suggestions in the next few days, I'll merge.

**Review by henrik242 — APPROVED** [review]

**Comment by f4lco** [comment]
@boris-petrov LGTM, but that null-check bothered me. It's actually hiding a regression in Gretty I take responsibility for.

The absent writer was unexpected. Rather than working around it, we should populate the writer field and send the response over the wire. If we skip sending the response (as the current patch does), the interactive mode hangs because it's waiting for that response.

After merging this PR, please also integrate 7ae75161d5b228f4b3fdaf15b1cd2164ab660dde to fix that. To verify that it works, one can use the itest of this PR and set `interactiveMode = "restartOnKeyPress"`, and observe that multiple successive reloads do not get stuck.

**Comment by boris-petrov** [comment]
@f4lco - thanks for the research and the fix! I've integrated it in this PR, check it out. It's not possible to somehow test this automatically, right?

**Comment by gbalthasar** [comment]
I don't know how to test automatically as the restart happens on external lib change for example. @tmohme added an integration test with manual testeing (see first post).

I still hope this is getting integrated for the next version so I can remove my manual fix soon. Sorry for fixing the NPE the "short" way but I'm not that deep into the code and for me it was to fastest way to get it running locally.

**Comment by f4lco** [comment]
@boris-petrov I'm not aware of any possibility to test easily - same for testing reload on changes (file or dependency change) and the interactive mode (reload on key press) - both of which were affected by this regression.

@gbalthasar don't be too sorry, that's simply what reviews are for. Thank you for your effort!

**Comment by boris-petrov** [comment]
@f4lco - thanks! The PR now looks good for merging I guess?

**Comment by f4lco** [comment]
@boris-petrov yes, go for it!

**Comment by boris-petrov** [comment]
Thanks, everyone, for the implementation, discussions, ideas and testing!

**Pull request merged**
