### PR TITLE
Support Jetty 11

### PR DESCRIPTION
**Pull request by f4lco**
I made Jetty 11 work. It was really a lot of work and many test failures. I do not expect the changes to be overly controversial, but here are a few talking points:

1. Is `jakarta.*` really a "system class"? This fixes a set of classloading issues in a logical way, but I wonder if they are indeed system classes, why isn't that enforced in Jetty by default? It also does not make sense to compile your app against one version of `jakarta-servlet-api`, and deploy to a server which ships with a different version. See 9d4bc4b7a46a0eab1b259a87a6116460c0ee3adf.
2. Jetty configuration files still have Jetty 10 in their DOCTYPE, not Jetty 11. Those files are not yet available - presumably they are once Jetty 11 is out of beta.
3. The logging debacle. Currently, there is no way out of the slf4j alpha, the logback alpha, and the missing support for logging configuration via Groovy inside logback. If it never comes back (who knows?) that is a major breaking change, and all Groovy log configuration scripts would have to be replaced in integration tests, and we would have to find another way to programmatically configure logback. Right now a couple of Gretty's logging toggles are defunct.

### CODE REVIEW

**Comment by boris-petrov** [comment]
@f4lco - thank you, yet again, for your hard work. I'm not sure how you can drink all the beer we owe you! :smile: 

You mention `many test failures` - you mean this was along the way, right? Because now I see that all tests are enabled and passing?

On your points:

1) I'm not exactly sure I understand completely what that means but what you've written here and as a comment in the commit makes sense to me. This reminded me of an [old commit](https://github.com/gretty-gradle-plugin/gretty/commit/291fd59147c4984a74196e6a9012e71f557903ba) I did a while ago - not sure if it is related in any way or if it can help you here.

2) Yep, I also tried searching in their GitHub repo and there are no mentions of version 11 yet. We'll fix them when they appear.

3) I opened an [issue](https://jira.qos.ch/browse/LOGBACK-1541) in their Jira. Let's see what they say.

Otherwise - amazing work as always! Thank you and feel free to merge when you want!

**Review by boris-petrov — APPROVED** [review]

**Comment by boris-petrov** [comment]
Oh, another thing I forgot. A lot of this code will be the same for Jetty 10, right? Perhaps it can be extracted in `master` and then when we rebase `gretty4` on it we can just apply the few changes there? Do you think that makes sense and is it worth it?

**Comment by f4lco** [comment]
>  I'm not sure how you can drink all the beer we owe you!

Many thanks 😄 

> You mention many test failures - you mean this was along the way, right? Because now I see that all tests are enabled and passing?

Yes, that was along the way to this PR. Have a look at the commit history - almost every commit is inspired by some sort of test failure. Actually, I was pleasantly surprised how much signal I got out of the test suite. I supposed they either fail all together or none. In reality however, many test cases exercised the code in a unique way leading to unique root causes & distinct fixes.

Regarding the other points: that's basically what I was thinking  - there's nothing to be done right now. I turned on notifications on the logback ticket you created, just in case. Thanks for that.

>  A lot of this code will be the same for Jetty 10, right?

Some sort of. I do know that a couple of patches apply to Jetty 10. However, they do not have a reasonable location on master. One would have to create the 'gretty-runner-jetty10' module in master first, and then possibly apply a subset of patches from this branch on top of it.

> Perhaps it can be extracted in master and then when we rebase gretty4 on it we can just apply the few changes there?

This won't work for two reasons: first, as per comment above, the file directories are distinct, mostly it's not shared code between Jetty 10 and 11 that is affected. Second, I gave up 'rebase' strategy, and starting cherry-picking relevant commits from master a while ago. There have a been a couple of conflicts, changes which do not have an equivalent in grett4 because they affect older runners, and even changes which had already been done to [gretty4](https://github.com/gretty-gradle-plugin/gretty/commits/gretty4). Time to remember those conflict resolutions & stabilize. When you cherry-pick and the build goes awry, it's easy to pinpoint and fix.

Thank you for your review!

**Comment by boris-petrov** [comment]
@f4lco - I wasn't sure where to ping you so here is as good as it gets I guess.

I saw you working on a Jetty 10 branch a few days ago which later disappeared. What was up with that? I still have it locally if you've deleted it by accident. :smile:

**Comment by f4lco** [comment]
@boris-petrov wow I guess my "work" does get noticed 😆 

Yeah, eventually, I gave up on it, because I realized without shifting requirements in a major way, that patch isn't going to get merged. This is what the current compatibility looks like:

|   | Java 8+ | Java 11+ |
|---|:-------:|:--------:|
| javax | Gretty 3.x | 🚫 |
| jakarta | 🚫 | Gretty 4.x |

... and Jetty 10 falls right in the upper corner, supporting javax, but having a minimum JDK requirement of 11.

So I am open to your suggestions to 'rescue' the patch, whether it's shifting requirements, or a technical solution. If you have a technical solution to the dilemma, I'd be glad to hear you out. I remember not reaching a definitive agreement on #161.  
To be honest I wouldn't have started my work on Jetty 10 if I had recalled that situation correctly. My fingers were flying faster than I got to think this one through 😄

**Comment by boris-petrov** [comment]
@f4lco - I was under the impression that Jetty 10 would be working on Java 8. If that's not so, I see no point in supporting it. The migration from Java 8 to Java 11 is a **much** bigger burden on people than renaming a bunch of imports from `javax.*` to `jakarta.*` so if they manage to do the former, they can definitely do the latter and just go to Jetty 11. Am I correct with these assumptions?

**Comment by f4lco** [comment]
Yes, I think you are correct, and we are on the same page here 👍 
Since the branch is up again, one can view the build history on Travis, too. Sadly the picture is quite clear: JDK 8 builds are the only ones to fail, and the reason is a compilation failure right in the Jetty 10 module: https://travis-ci.org/github/gretty-gradle-plugin/gretty/builds/747443668
You're welcome and thanks for reaching out!

**Pull request merged**
