### PR TITLE
Remove duplicate publication in gretty subproject

### PR DESCRIPTION
**Pull request by wolfs**
https://github.com/gretty-gradle-plugin/gretty/pull/197 introduced a duplicate publication in the `gretty` plugin project. That will probably cause a failure when publishing the plugin to Gradle's plugin portal.

This PR removes the duplicate publication by introducing convention plugins for the gretty libraries and the gretty Gradle plugin, both configuring different publications.

### CODE REVIEW

**Comment by wolfs** [comment]
@boris-petrov Please take a look.

**Comment by boris-petrov** [comment]
Well, I don't really have a good idea what this whole thing does so I'll take @wolfs' word that it's OK. :smile: @f4lco - if you have no objections, please merge. I guess when @javabrett gets to it, he'll say if publishing is fine. :)

**Comment by f4lco** [comment]
I *think* that will work. I also like the structure within a buildSrc project. The only thing I am still concerned about is #192. 
 - Could you please outline necessary steps to publish to the Gradle Plugin Portal?
 - That will probably be done through / with aid of "java-gradle-plugin", right?
 - I assume that all of Gretty's components will be available from Gradle's plugin repository. What does that mean with regard to the publications? Will each build module eventually have a "plugin publication"? Will the "mavenJava" publication eventually cease to exist?

@wolfs I think 50% of this PR is having a better structure and fixing that duplicate publication. The other 50% is outlining next steps and desired project state. Please help us find it. You may also not directly answer to the questions above; if you have it, please give us the bigger picture or recommendations as you see fit.

**Comment by wolfs** [comment]
Yes, https://github.com/gretty-gradle-plugin/gretty/issues/192 is concerning. I added a comment to it.

Regarding the publications: The publication are per project, so they will continue to exist. All of the publications are `MavenPublication`s, even the `pluginMaven` publication in the `gretty` subproject. The `com.gradle.plugin-publish` takes all publications of the `gretty` subproject and publishes them to the plugin portal (aka its Maven repository).

So in order to make publication continue working to the plugin portal for the gretty subproject, this PR needs to be merged. For discussing where to release the remaining artifacts let's discuss on https://github.com/gretty-gradle-plugin/gretty/issues/192. No matter how we continue here, we need this PR.

**Comment by boris-petrov** [comment]
I'm fine with this, @f4lco - feel free to merge when you're OK.

**Comment by boris-petrov** [comment]
We have to do the same (aka cherry-pick the commits) on the 3.x branch too, right?

**Comment by wolfs** [comment]
I think so.

**Pull request merged**
