### PR TITLE
Make Gretty aware of Gradle Java Toolchain (v4.x)

### PR DESCRIPTION
**Pull request by mr-serjey**
Gretty plugin run containers as a separate java process using the same java that is used by Gradle.

However since Gradle introduced [Toolchains for JVM projects](https://docs.gradle.org/current/userguide/toolchains.html), the expectation is that Gretty plugin will also respect the java toolchain DSL and run containers using the specified JDK instead of one that used by Gradle.

Currently if java toolchain DSL is declared in a project, the classes compiled by the JDK specified there (e.g. v21), at the same time Gretty plugin uses Gradle JDK (e.g. v11), as result the container fails to start since JVM v11 can't load classes of java v21.

**This PR purposes changes into Gretty plugin to respect java toolchain DSL:**
- add ServerConfig.jvmExecutable String (optional value)
- StartBaseTask sets ServerConfig.jvmExecutable (if java toolchain DSL specified)
- DefaultLauncher sets JavaExecSpec.executable for Gradles javaexec to start the right java version (if jvmExecutable set)
- If no toolchain DSL specified the default JavaExecParams.executable is used (Gradle JVM)

With the following DSL the project going to use java 21 both to compile classes and to run them in container using Gretty plugin:
```
build.gradle
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
```

Related issue: #261 

**Complementary changed of tests:**
- added tests for Gradle Java Toolchain functionality
- added extra matrix cases in `ci.yml` to cover Gradle Java Toolchain functionality (Java 11+17 and java 17+21)
- added `docker_integration_tests.sh` that runs all tests inside docker similarly to ci.yml (helped a lot locally on Windows machine)
- migrated groovy classes of test applications into java, to avoid groovy bytecode incompatibility on high java versions

**NOTE: This PR is a forward-port of v3.x PR https://github.com/gretty-gradle-plugin/gretty/pull/306**

### CODE REVIEW

**Review by boris-petrov — APPROVED** [review]

**Comment by mr-serjey** [comment]
Hi @boris-petrov and @f4lco, please share your plans regarding this PR, are there any timeline for review, merge, release?

**Comment by boris-petrov** [comment]
@mr-serjey sorry, I'll merge and release next week.

**Comment by boris-petrov** [comment]
@mr-serjey thanks again for that! I'll release it the end of this week or beginning of next.

**Comment by boris-petrov** [comment]
Released! Thanks @mr-serjey!

**Pull request merged**
