### PR TITLE
Remove known deprecations in Gretty

### PR DESCRIPTION
**Pull request by f4lco**
This patch removes a number of long-standing deprecations in Gretty. All deprecations have suitable replacements, because they have mostly been renamed.

### CODE REVIEW

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by boris-petrov** [comment]
@f4lco - thanks for the PR! Do you mind just making https://github.com/gretty-gradle-plugin/gretty/pull/202/files#diff-7a953dc8c046b012ef0e243258e0509ac0aaa487db484c2c24c41f2d84b273ac in a separate commit so that we/you can cherry-pick it in the `gretty-3.x` branch? I think it's a good change for there also?

**Comment by f4lco** [comment]
@boris-petrov sure, I don't mind. Please tell me once more which commits you are exactly referring to and I will cherry-pick them on 3.x. The link does not work - I guess you swooped in just before a rebase (I fixed a typo in a commit message). My bad!

**Comment by boris-petrov** [comment]
Strange, the link doesn't work for you right now? It does for me... I meant just the change on [this line](https://github.com/gretty-gradle-plugin/gretty/blob/master/integrationTests/jacocoInstantiateTasks/build.gradle#L35). I think it's OK to do it on 3.x too. But I think it's not in a separate commit so I guess you can do it independently please?

**Comment by f4lco** [comment]
Ah, I did not get how the link works at all. I thought the hash in the URL must be commit IDs. Yes, will do 👍

**Comment by boris-petrov** [comment]
Thanks!

**Comment by f4lco** [comment]
c2dcb5339ad8910b12919a1ec2d7143c74e712ba

**Pull request merged**
