### PR TITLE
Use appropriate class loader for servermanger commands

### PR DESCRIPTION
**Pull request by smhc**
Additional change to address restart issues with issue 293

### CODE REVIEW

**Comment by boris-petrov** [comment]
@smhc thanks for that! Seems good to me. You could extract a method that does that (although I don't see a good way of reusing it in the already-existing place).

@f4lco please take a look and give your opinion - you definitely know the code better than me. I guess it makes sense that all `startServer` calls are surrounded with classloader-modification.

**Comment by boris-petrov** [comment]
Thanks again for this and sorry for taking so long to merge it! @f4lco please take a look when you can and we can always fix anything you want after that. :)

**Comment by f4lco** [comment]
Thank you so much @smhc for your contribution. Indeed, the missing guards have been an oversight!

**Comment by boris-petrov** [comment]
Released in 4.1.1. Thanks!

**Comment by smhc** [comment]
Will there be a 3.x release with theses changes?

**Comment by boris-petrov** [comment]
@smhc for sure! I wanted to fix #297 before that for the 3.x branch. Hopefully early next week. Feel free to do it before me if you have the time! :smile:

**Comment by boris-petrov** [comment]
@smhc I've released 3.1.2. Sorry for the delay!

**Pull request merged**
