### PR TITLE
Replace internal Gradle API usage with public API

### PR DESCRIPTION
**Pull request by octylFractal**
Cherry-pick of #263 onto `gretty-3.x`.

### CODE REVIEW

**Comment by boris-petrov** [comment]
Thank you!

**Comment by boris-petrov** [comment]
@f4lco please merge it if you think it's fine. It's 1:1 with the other one so... :)

**Comment by octylFractal** [comment]
@f4lco is there anything blocking this? We would like a release of 3.x with this ASAP for some tests in Gradle.

**Comment by boris-petrov** [comment]
@octylFractal I'll release this tomorrow. :)

**Comment by octylFractal** [comment]
Thanks.

**Comment by boris-petrov** [comment]
@octylFractal I've released 3.0.9. Let us know if it works as expected.

**Pull request merged**
