### PR TITLE
[VOTE] Release 2.3.0

### PR DESCRIPTION
**Pull request by javabrett**
Vote-only, don't merge. To vote, just add yourself as a Reviewer and add any comments.  Replaces #69 .  Snapshots available e.g. https://oss.jfrog.org/artifactory/oss-snapshot-local/org/gretty/gretty-core/2.3.0-SNAPSHOT/ .

Release motivation: Gradle 5.0 support.  2.2 has a couple of known blocker issues which have now been addressed.

Known issues:
- Gradle 5 deprecation (#80) 
- Config-time performance issues still not fully-addressed (#68)

/cc @henrik242 @boris-petrov @wolfs @chali

### CODE REVIEW

**Comment by boris-petrov** [comment]
I think we can also merge https://github.com/gretty-gradle-plugin/gretty/pull/40 for this release, what do you think? But @henrik242 should update Groovy to the latest 2.5.4 before that.

**Comment by javabrett** [comment]
@boris-petrov @henrik242 the issues I see with #40 are:
- that PR targets `master` not `gretty-2.x`, so unless rebased it won't apply to this 2.3 release from the `gretty-2.x` branch.  I should probably have called-out more clearly that this is a maintenance/non-master release.
- 2.3/2.x was intended to be bugfix/maintenance only, but given master/3.0 is not immediately-ready, and the changes seemed small, 2.3 can be released with Gradle 5.0 support/fixes.
- CI has not been passing.  I've just bumped it to Groovy 2.5.4 and rebased to current master, so tests will re-run now.

That said - what are we missing if we can't incorporate #40 in 2.3?  If it's only better JDK11 support, that should remain a 3.0 target I think.

**Comment by henrik242** [comment]
That said, we should merge #40 asap. None of my builds have been at jdk8 for several months.

**Comment by javabrett** [comment]
> That said, we should merge #40 asap. None of my builds have been at jdk8 for several months.

Yes let's continue the discussion over at #40, which needs possibly quite some work yet - I've left a comment.

**Comment by chali** [comment]
@javabrett did everything went ok during release? I don't see `gretty-starter` in version 2.3.0 https://bintray.com/javabrett/maven/org.gretty#files/org%2Fgretty%2Fgretty-starter

**Comment by javabrett** [comment]
AFAIK the release shipped OK, but I do notice no `org.gretty:gretty-starter:2.3.0` as you point out.  Will have to check what happened to it.  Is it blocking you?

I see it built in 2.3.0 shapshots and 2.4.0 snapshots ... maybe something didn't upload properly.

**Comment by chali** [comment]
That is strange. Thank you for looking into this. Hopefully, you will be able to release just the missing module but 2.3.1 release is fine too.

**Pull request merged**
