### PR TITLE
Project fork plugin id and deployment changes

### PR DESCRIPTION
**Pull request by javabrett**
* Plugin id org.akhikhl.gretty -> org.gretty.
* Changed artifacts group org.akhikhl.gretty -> org.gretty.
* Updated developerId.
* Added bintrayRepo and bintrayPackage variables to be supplied by Travis
  as BINTRAY_REPO and BINTRAY_PACKAGE

Via Travis build (when pushed as `master`) this pushes a snapshot to http://oss.jfrog.org/oss-snapshot-local/org/gretty/gretty/2.0.1-SNAPSHOT/ .

Note that you cannot test the actual deployment, as that requires an encrypted keys change which will follow.

### CODE REVIEW

**Comment by javabrett** [comment]
@henrik242 @boris-petrov @woldie @wolfs PTAL and advise if you can review.

**Comment by boris-petrov** [comment]
Looks good to me. There’s a few pull-requests in the “original” repo that are good to be merged before a new release - there is one for Gradle 4.6 support, I have one for Tomcat 8.5.2+ support. Maybe some of the others too. Thanks for taking the time and initiative to do this!

**Comment by wolfs** [comment]
Hey @javabrett! Does this mean you are taking over maintaining the Gretty plugin now? That would be great!
If you are now the maintainer of this for it would be great if you could answer to https://discuss.gradle.org/t/revive-gretty-once-again/25961.

What are your plans how to continue with this? If this becomes the "official" fork, the official Gradle documentation should also point to this plugin instead of `org.akhikhl.gretty`.

I also would like to know @akhikhl's thoughts on this fork.

**Comment by wolfs** [comment]
Ah, I found [this discussion](https://github.com/akhikhl/gretty/pull/417#issuecomment-367142536).

Are there some other discussions going on somewhere? It would be great to get the readme of this repository updated.

**Comment by henrik242** [comment]
I guess it would be a good idea to make a handful of people admins for this project right away. From personal experience that made the Spotbugs project move forward easily when it forked from Findbugs.

**Comment by henrik242** [comment]
@javabrett It looks like the issue tracker is missing from this project, could you enable it?

**Comment by javabrett** [comment]
@henrik242 I had no idea that was off by - default. On now.

**Pull request merged**
