### PR TITLE
v3. Downgrade commons-cli to fix product run

### PR DESCRIPTION
**Pull request by aindlq**
Product runs are currently broken because of the incompatibility between `CliBuilder` and `commons-cli` version that is used in gretty. 

Gretty is using `commons-cli` version that is incompatible with `CliBuilder` from groovy 3.x. `CliBuilder` in groovy 3.x is accessing  `numberOfArgs` property - https://github.com/apache/groovy/blob/GROOVY_3_0_22/subprojects/groovy-cli-commons/src/main/groovy/groovy/cli/commons/CliBuilder.groovy#L555

but it was renamed in `commons-cli` version after `1.3.1` to `argCount`, see https://github.com/apache/commons-cli/blob/cli-1.3.1/src/main/java/org/apache/commons/cli/Option.java#L72 vs currently used one https://github.com/apache/commons-cli/blob/commons-cli-1.5.0/src/main/java/org/apache/commons/cli/Option.java#L76 

Exception when trying to run product generated with gretty 3.1.4:

```
Exception in thread "main" groovy.lang.MissingPropertyException: No such property: numberOfArgs for class: org.apache.commons.cli.Option
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:65)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetPropertySafe(AbstractCallSite.java:448)
	at groovy.cli.commons.OptionAccessor.getTypedValue(OptionAccessor.groovy:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
	at groovy.cli.commons.OptionAccessor.getProperty(OptionAccessor.groovy:150)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at org.akhikhl.gretty.Runner.main(Runner.groovy:34)

```

### CODE REVIEW

**Comment by boris-petrov** [comment]
Hi @aindlq, thanks for the PR! So why not just use the new variable name instead of downgrading the dependency? Are there more problems?

**Comment by boris-petrov** [comment]
`master` and v3 are developed in parallel because of the javax vs jakarta namespace change. So you might want to cherry-pick the commit from `master` that I mentioned in this PR and replace your commit (just to be consistent in the two branches) and then I'll merge this. After that if you can also open a PR against `master` with the downgrade of the `commons-cli` package - that would be great!

**Comment by aindlq** [comment]
done https://github.com/gretty-gradle-plugin/gretty/pull/315

**Comment by boris-petrov** [comment]
Thank you! I'll wait for the tests to finish and will merge both. Do you need this released quickly?

**Comment by aindlq** [comment]
Thanks! 

It is not ultra urgent but highly appreciated, we use gretty in https://github.com/researchspace/researchspace and currently doing a new major release, would be nice to have things working without too much hacks.

**Comment by boris-petrov** [comment]
Will do! I'll create a new release later today. Thanks again for the PRs!

**Comment by aindlq** [comment]
Thank you!

**Comment by boris-petrov** [comment]
Released in 4.1.6 and 3.1.5! Thank you again!

**Comment by aindlq** [comment]
Thank you!!!

**Pull request merged**
