### PR TITLE
Enable Gradle warnings

### PR DESCRIPTION
**Pull request by boris-petrov**
So we can start fixing them.

### CODE REVIEW

**Comment by boris-petrov** [comment]
I was actually expecting to see this deprecation warning in the Gradle 7 build:

```
Invocation of Task.project at execution time has been deprecated. This will fail with an error in Gradle 8.0. Consult the upgrading guide for further information: https://docs.gradle.org/7.6/userguide/upgrading_version_7.html#task_project
        at org.gradle.configurationcache.DeprecatedFeaturesListenerManagerAction$DeprecatedFeaturesListener.onProjectAccess(DeprecatedFeaturesListenerManagerAction.kt:70)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:462)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:444)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:83)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:69)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:433)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:221)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:192)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy1/jdk.proxy1.$Proxy121.onProjectAccess(Unknown Source)
        at org.gradle.api.internal.AbstractTask.notifyProjectAccess(AbstractTask.java:1068)
        at org.gradle.api.internal.AbstractTask.getProject(AbstractTask.java:235)
        at org.gradle.api.DefaultTask.getProject(DefaultTask.java:59)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
        at org.akhikhl.gretty.AppStartTask_Decorated.getProperty(Unknown Source)
        at org.akhikhl.gretty.AppStartTask.getStartConfig(AppStartTask.groovy:57)
        at org.akhikhl.gretty.AppStartTask_Decorated.getStartConfig(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask.getLauncherConfig(StartBaseTask.groovy:172)
        at org.akhikhl.gretty.StartBaseTask.action(StartBaseTask.groovy:53)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        ...
```

But I guess the `appStart` task is not tested directly, is that so @f4lco?

**Review by f4lco — APPROVED** [review]
🥇

**Comment by boris-petrov** [comment]
Thanks @f4lco! Any ideas about [this comment](https://github.com/gretty-gradle-plugin/gretty/pull/281#issuecomment-1369579865) however?

**Comment by f4lco** [comment]
> Thanks @f4lco! Any ideas about [this comment](https://github.com/gretty-gradle-plugin/gretty/pull/281#issuecomment-1369579865) however?

That's very plausible that the integration test do not depend on this particular task, we have a couple of blind spots there, e.g., also for `buildProduct`.

**Pull request merged**
