### PR TITLE
Remove unused input for task

### PR DESCRIPTION
**Pull request by chali**

### CODE REVIEW

**Comment by javabrett** [comment]
Thanks.  I need to add something to Travis to cross-test with Gradle 5.0 beta/GA.

> chali changed the base branch from master  to gretty-2.x

Just wanted to check on this - so far we've only been considering the (unreleased) master/3.0 branch for Gradle 5 support, although this hasn't been discussed at length.  Is there a specific need in Gretty 2.x?

**Comment by chali** [comment]
Hi @javabrett thanks for looking into this. I haven't seen any releases from 3.x so I assumed that 2.x is still the right place for this fix. Do you plan to release 3.x as the first version to support Gradle 5.0? Will be easy to migrate from 2.x to 3.x? I'm from a centralized build team and we will have quite a big migration to move all our customers to Gradle 5.0. Ideally, I would love to just upgrade plugin version to make build compatible so fix backported even to 2.x would be really helpful to minimize the number of changes related to the Gradle upgrade.

**Comment by javabrett** [comment]
Regarding Gradle 5.0 branch - the current loose thinking for Gretty 3.0 is:

- Remove ancient JDK support: JDK7
- Remove ancient/EOL container support: very old Jetty 7/8, Tomcat 7/8 releases
- Remove ancient Gradle version support (pre 4.0??)
- Add JDK11 support
- Add Gradle 5 support
- Add support for new Spring Boot, Groovy
- Gretty 2.x: none of the above.

So Gretty 2.x is currently pictured as terminal/maintenance.  Many issues started cropping-up with very old container support on new JDKs etc., to 3.0 attempts to cut the cruft and add new support.  I'm keen to understand how heavy the crossover would be for combinations like Jetty 7, JDK?, Gradle 5.  I suspect you are right and Gradle 5 might be the biggest want.

That said there are very few active contributors at the moment and the project was forked from dormancy, so we could definitely use additional contributors.

**Comment by javabrett** [comment]
> Will be easy to migrate from 2.x to 3.x?

I'd hope so, but no promises :).  One current difference is that recent releases have not been pushed to Maven Central, so JCenter is required in buildcripts and dependencies.

3.0.0 snapshots are already on JFrog OSS if you want to do some testing.

**Comment by chali** [comment]
When do you think 3.0 could get out? I assume it could take a while. Gradle 5.0 will be released next Monday. After that, users with 2.x will have some broken features. Right now this issue is the only one we have found with Gradle 5.0 so it might be possible to backport Gradle 5 support into 2.x quite easily. If new issues will arise we can evaluate the situation and see if it still possible support Gradle 5.0 in 2.x. I can help you with that part. What do you think?

**Comment by javabrett** [comment]
Re 3.0 - there's a performance story #68 which I had hoped could be fixed in 2.x before 3.0 was released, but that may not be possible as it is a reasonably complex issue.

If there turns out to be a small number of low-impact fixes to get 2.x to support Gradle 5.0 then I would certainly be open to that.  I'd certainly appreciate any assistance with that effort.  I'm thinking that initially at-least it should be possible to build Gretty with Gradle 4.x and cross-test it with 4.x and 5.0, assuming there's no known issue with that (provided any compatibility issues are addressed)?

Let's continue the Gradle 5.0 discussion on #93.

**Comment by javabrett** [comment]
This could use a failing->passing test in `integrationTests`, which should be easy to set-up since `buildProduct` can be called on any of the projects there, and produces the error.

**Comment by javabrett** [comment]
Thanks! :cake:

**Pull request merged**
