### PR TITLE
Fix Invalid plugin ID 'org.gretty' when running publishPlugins

### LINKED ISSUE #208: Release (3.0.4): Invalid plugin ID 'org.gretty': multiple plugins are using the same ID
I'm attempting to release 3.0.4 but am facing:

```
./gradlew publishPlugins
...
* What went wrong:
Execution failed for task ':libs:gretty:publishPlugins'.
> Invalid plugin ID 'org.gretty': multiple plugins are using the same ID
```

... along with the Bintray deadline.  Any thoughts welcome.

Possibly related: https://discuss.gradle.org/t/invalid-plugin-id-plugin-name-multiple-plugins-are-using-the-same-id/28545

CC @wolfs @boris-petrov

### PR DESCRIPTION
**Pull request by javabrett**
Fixed #208 .

### CODE REVIEW

**Comment by boris-petrov** [comment]
@javabrett - I'm not sure what this does or why it fixes the problem, but if it does, I'm fine with it. Go ahead and publish 3.0.4 and if this is "incorrect" in some way, we can fix it later.

@wolfs - any idea why this was needed and why it was changed the way it was?

**Review by boris-petrov — APPROVED** [review]

**Comment by boris-petrov** [comment]
Actually now I see that this code wasn't touched with @wolfs' changes.

**Comment by wolfs** [comment]
Thank you! It seems like the id in the gradlePlugins and the pluginBundle block need to be the same.

**Comment by javabrett** [comment]
Just a release update related to this ... 3.0.4 is live in Bintray (to beat the deadline), but even with this fix I got strange "looks like a new plugin" message from plugins.gradle.org, see #208 .  So waiting for 3.0.4 to be able to be published there.

**Comment by javabrett** [comment]
I already have (but possibly lapsed) `org.gretty` permissions in Maven Central, but need to test releasing something there.

**Comment by boris-petrov** [comment]
@javabrett - thanks! Keep us posted on when the Gradle team approves the plugin.

As for the test release - we have a couple of PRs lined up for merging right now so when 3.0.4 is out and we've merged them, you could do a 3.0.5 on Maven Central.

**Comment by ljacomet** [comment]
Hello,

I confirm that the plugin looks _new_ from the Gradle Plugin Portal perspective.
This is because the new version uses `org.gretty:gretty` as the JAR coordinates instead of `gradle.plugin.org.gretty:gretty` previously. Note that this is a good change IMO.

The plan is to approve the plugin under these new coordinates.

**Comment by boris-petrov** [comment]
@ljacomet - thank you for the comment. I'm not sure what that means exactly - this won't change where users resolve the plugin from, right? That is, people will still do `id 'org.gretty' version '3.0.4'`?

**Comment by boris-petrov** [comment]
I saw your edit now. In my project I have:

```gradle
plugins {
  id 'org.gretty' version '3.0.3' apply false
}

... // later

apply plugin: 'org.gretty'
```

You're saying this will change?

**Comment by ljacomet** [comment]
No, what changes is when using the legacy system:
```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "org.gretty:gretty:3.0.4" // was prefixed with gradle.plugin before
  }
}

apply plugin: "org.gretty"
```

**Comment by boris-petrov** [comment]
I see, thank you. @javabrett, @f4lco - I'm OK with this change even though it should require a major-version release... are you OK too?

**Comment by f4lco** [comment]
@boris-petrov that's fine with me 👍  I'm not sure about the major-version. I don't see how it would fit within the existing 3.x / 4x. split. I'm fine with "if you are still using the legacy plugin application and you want to opt-in to the upgrade, you also need to change the dependency coordinate" and spare the effort.

**Comment by boris-petrov** [comment]
Exactly, yes. For users it's a trivial change so we can go with that. OK, great, 3.0.4 is out and I'm already using it and loving it! :smile:

**Comment by wolfs** [comment]
@javabrett I suppose you could use both group ids before, since the plugin artifact was published with `org.gretty` on jcenter and with `gradle.plugin.org.gretty` on the plugin portal. So now both artifacts (jcenter & the plugin portal) have the same coordinates.

**Pull request merged**
