### PR TITLE
Fix remaining plugin validation problems

### PR DESCRIPTION
**Pull request by wolfs**
This PR fixes the remaining validation problems of the tasks.

### CODE REVIEW

**Comment by wolfs** [comment]
@boris-petrov @f4lco Can you please take a look?

**Comment by boris-petrov** [comment]
Looks great to me! @f4lco - please directly merge if you think it's OK too.

**Comment by wolfs** [comment]
@f4lco I removed applying the `java-gradle-plugin`, since that adds a new publication as well, and I would like to understand publishing first. I'll do that in a separate PR.

**Comment by f4lco** [comment]
LGTM, thanks again, @wolfs!

**Pull request merged**
